//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinManager.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel download.
        /// </summary>
        public static string cancelUpdateDownloadButton {
            get {
                return ResourceManager.GetString("cancelUpdateDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string checkForUpdatesButton {
            get {
                return ResourceManager.GetString("checkForUpdatesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for updates when WinManager is shown for the firs tttime after its launch.
        /// </summary>
        public static string checkUpdateOnFirstShowCheckBox {
            get {
                return ResourceManager.GetString("checkUpdateOnFirstShowCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string closeButton {
            get {
                return ResourceManager.GetString("closeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing the window.
        /// </summary>
        public static string closingWindow {
            get {
                return ResourceManager.GetString("closingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing failed.
        /// </summary>
        public static string closingWindowFailed {
            get {
                return ResourceManager.GetString("closingWindowFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue download.
        /// </summary>
        public static string continueUpdateDownloadButton {
            get {
                return ResourceManager.GetString("continueUpdateDownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while WinManager update {0} is beeing downloaded..
        /// </summary>
        public static string downloadingUpdateMessage {
            get {
                return ResourceManager.GetString("downloadingUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update.
        /// </summary>
        public static string downloadingUpdateTitle {
            get {
                return ResourceManager.GetString("downloadingUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled keyboard shortcuts for list of running apps.
        /// </summary>
        public static string enabledAppsShortcutsHeader {
            get {
                return ResourceManager.GetString("enabledAppsShortcutsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled keyboard shortcuts for list of foreground app open windows.
        /// </summary>
        public static string enabledWindowsShortcutsHeader {
            get {
                return ResourceManager.GetString("enabledWindowsShortcutsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting WinManager.
        /// </summary>
        public static string exitAnnouncement {
            get {
                return ResourceManager.GetString("exitAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Explorer.
        /// </summary>
        public static string fileExplorer {
            get {
                return ResourceManager.GetString("fileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force quitting the app.
        /// </summary>
        public static string forceQuittingApp {
            get {
                return ResourceManager.GetString("forceQuittingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch WinManager on Windows startup.
        /// </summary>
        public static string launchOnStartupCheckBox {
            get {
                return ResourceManager.GetString("launchOnStartupCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch installer.
        /// </summary>
        public static string launchUpdateInstallerButton {
            get {
                return ResourceManager.GetString("launchUpdateInstallerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update installer has been downloaded. Do you want to launch it?.
        /// </summary>
        public static string launchUpdateInstallerMessage {
            get {
                return ResourceManager.GetString("launchUpdateInstallerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch update installer.
        /// </summary>
        public static string launchUpdateInstallerTitle {
            get {
                return ResourceManager.GetString("launchUpdateInstallerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No apps found.
        /// </summary>
        public static string noAppsFound {
            get {
                return ResourceManager.GetString("noAppsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notepad.
        /// </summary>
        public static string notepadOverride {
            get {
                return ResourceManager.GetString("notepadOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not now.
        /// </summary>
        public static string notNowButton {
            get {
                return ResourceManager.GetString("notNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version of WinManager {0} is up to date..
        /// </summary>
        public static string noUpdateAvailableMessage {
            get {
                return ResourceManager.GetString("noUpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update available.
        /// </summary>
        public static string noUpdateAvailableTitle {
            get {
                return ResourceManager.GetString("noUpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No windows found.
        /// </summary>
        public static string noWindowsFound {
            get {
                return ResourceManager.GetString("noWindowsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open windows.
        /// </summary>
        public static string openWindowsLabel {
            get {
                return ResourceManager.GetString("openWindowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitting the app.
        /// </summary>
        public static string quittingApp {
            get {
                return ResourceManager.GetString("quittingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitting failed.
        /// </summary>
        public static string quittingAppFailed {
            get {
                return ResourceManager.GetString("quittingAppFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running apps.
        /// </summary>
        public static string runningAppsLabel {
            get {
                return ResourceManager.GetString("runningAppsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settingsButton {
            get {
                return ResourceManager.GetString("settingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for WinManager.
        /// </summary>
        public static string settingsDialogTitle {
            get {
                return ResourceManager.GetString("settingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinManager started.
        /// </summary>
        public static string startAnnouncement {
            get {
                return ResourceManager.GetString("startAnnouncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New WinManager version {0} is available. You currently have version {1}. Do you want to download the update and run its installation now?.
        /// </summary>
        public static string updateAvailableMessage {
            get {
                return ResourceManager.GetString("updateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinManager update available.
        /// </summary>
        public static string updateAvailableTitle {
            get {
                return ResourceManager.GetString("updateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update was not successful. Please verify that you are connected to the Internet..
        /// </summary>
        public static string updateCheckFailedMessage {
            get {
                return ResourceManager.GetString("updateCheckFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update failed.
        /// </summary>
        public static string updateCheckFailedTitle {
            get {
                return ResourceManager.GetString("updateCheckFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update download was not successful. Please verify that you are connected to the Internet..
        /// </summary>
        public static string updateDownloadFailedMessage {
            get {
                return ResourceManager.GetString("updateDownloadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update download failed.
        /// </summary>
        public static string updateDownloadFailedTitle {
            get {
                return ResourceManager.GetString("updateDownloadFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update is being downloaded. Do you want to cancel the download?.
        /// </summary>
        public static string updateDownloadInProgressMessage {
            get {
                return ResourceManager.GetString("updateDownloadInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update download in progress.
        /// </summary>
        public static string updateDownloadInProgressTitle {
            get {
                return ResourceManager.GetString("updateDownloadInProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update.
        /// </summary>
        public static string updateDownloadProgressLabel {
            get {
                return ResourceManager.GetString("updateDownloadProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update installer is running. Please finish or cancel the installation before downloading the update again..
        /// </summary>
        public static string updateInstallRunningMessage {
            get {
                return ResourceManager.GetString("updateInstallRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update installer is running.
        /// </summary>
        public static string updateInstallRunningTitle {
            get {
                return ResourceManager.GetString("updateInstallRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to windows.
        /// </summary>
        public static string windowsCount {
            get {
                return ResourceManager.GetString("windowsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yesButton {
            get {
                return ResourceManager.GetString("yesButton", resourceCulture);
            }
        }
    }
}
